#ifndef INDUSTRIALWORKERZONE_H
#define INDUSTRIALWORKERZONE_H

enum IndustrialWorkerZone {
    TECH,
    AGRICULTURAL,
    CONSTRUCTION,
    EDUCATIONAL,
    ENTERTAINMENT
};

#endif /* INDUSTRIALWORKERZONE_H */
