#ifndef GROUP_PROJECT_1___SIM_CITY_RACETYPE_H
#define GROUP_PROJECT_1___SIM_CITY_RACETYPE_H

enum RaceType {
    WHITE,
    BLACK,
    AMERICAN_INDIAN,
    ASIAN,
    PACIFIC_ISLANDER,
    HISPANIC
};

#endif //GROUP_PROJECT_1___SIM_CITY_RACETYPE_H
